name: Notion to Cloudflare Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Notion to HTML converter (TIL posts)
        run: python notion_to_html.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Generate TIL index grouped by tags
        run: python generate_til_index.py

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "🤖 Auto-update from Notion TIL database + index + RSS" || echo "No changes"
          git push
      - name: Debug file tree
        run: |
          echo "📂 File structure:"
          ls -R til/